<Project>
  <PropertyGroup>
    <Authors>Ryan Martin</Authors>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/universehq/extensions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/universehq/extensions</RepositoryUrl>
  </PropertyGroup>
</Project>
